# Generated by Django 5.0.6 on 2024-07-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='servicee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.TextField(max_length=13)),
                ('address', models.TextField(max_length=50)),
                ('city', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=15)),
                ('pincode', models.CharField(max_length=10)),
                ('date', models.DateTimeField()),
                ('service', models.CharField(choices=[('tv_repair', 'TV Repair'), ('laptop_repair', 'Laptop Repair'), ('mobile_repair', 'Mobile Repair'), ('home_appliances_repair', 'Home Appliances Repair')], max_length=122)),
            ],
        ),
    ]
