# Generated by Django 5.0.6 on 2024-07-27 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elect', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicee',
            old_name='service',
            new_name='service_type',
        ),
    ]
