# Generated by Django 5.0.6 on 2024-07-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elect', '0003_servicee_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='rev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('review', models.TextField()),
            ],
        ),
    ]
